[build]
  functions = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "multer", "tesseract.js"]

[dev]
  functionsPort = 8888