[build]
  functions = "functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "multer", "tesseract.js"]

[dev]
  functionsPort = 8888